# Generated by Django 3.1.5 on 2021-01-23 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm', models.CharField(blank=True, choices=[('Armstrong', 'Armstrong'), ('Brown', 'Brown'), ('Caldwell', 'Caldwell'), ('Center Street North', 'Center Street North'), ('Center Street South', 'Center Street South'), ('Cloudman', 'Cloudman'), ('Eighth Street East', 'Eighth Street East'), ('Eighth Street South', 'Eighth Street South'), ('Eighth Street West', 'Eighth Street West'), ('Field', 'Field'), ('Fitten', 'Fitten'), ('Folk', 'Folk'), ('Freeman', 'Freeman'), ('Fulmer', 'Fulmer'), ('Glenn', 'Glenn'), ('Goldin House', 'Goldin House'), ('Graduate Living Center', 'Graduate Living Center'), ('Gray House', 'Gray House'), ('Hanson', 'Hanson'), ('Harris', 'Harris'), ('Harrison', 'Harrison'), ('Hayes House', 'Hayes House'), ('Hefner', 'Hefner'), ('Howell', 'Howell'), ('Matheson', 'Matheson'), ('Maulding', 'Maulding'), ('Montag', 'Montag'), ('Nelson Shell', 'Nelson Shell'), ('North Avenue East', 'North Avenue East'), ('North Avenue North', 'North Avenue North'), ('North Avenue South', 'North Avenue South'), ('North Avenue West', 'North Avenue West'), ('Perry', 'Perry'), ('Smith', 'Smith'), ('Stein House', 'Stein House'), ('Tenth and Home Bldg A', 'Tenth and Home Bldg A'), ('Tenth and Home Bldg B', 'Tenth and Home Bldg B'), ('Tenth and Home Bldg C', 'Tenth and Home Bldg C'), ('Tenth and Home Bldg D', 'Tenth and Home Bldg D'), ('Tenth and Home Bldg E', 'Tenth and Home Bldg E'), ('Tenth and Home Bldg F', 'Tenth and Home Bldg F'), ('Towers', 'Towers'), ('Woodruff North', 'Woodruff North'), ('Woodruff South', 'Woodruff South'), ('Zbar', 'Zbar')], max_length=200)),
                ('course_schedule', models.ManyToManyField(blank=True, related_name='course_schedule', to='tracker.Course')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date test taken')),
                ('is_positive', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
