# Generated by Django 3.1.5 on 2021-01-23 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_auto_20210123_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.student'),
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(blank=True, choices=[('760 Spring Street', '760 Spring Street'), ('Allen Sustainable Eduation Building', 'Allen Sustainable Eduation Building'), ('Boggs Building', 'Boggs Building'), ('Bunger Henry Building', 'Bunger Henry Building'), ('Cherry Emerson Building', 'Cherry Emerson Building'), ('Clough Undergraduate Learning Commons', 'Clough Undergraduate Learning Commons'), ('College of Computing', 'College of Computing'), ('GUGGENHEIM AEROSPACE BUILDING', 'GUGGENHEIM AEROSPACE BUILDING'), ('ENGINEERING SCIENCE & MECHANICS', 'ENGINEERING SCIENCE & MECHANICS'), ('HOWEY PHYSICS BUILDING', 'HOWEY PHYSICS BUILDING'), ('INSTRUCTIONAL CENTER', 'INSTRUCTIONAL CENTER'), ('KENDEDA BUILDING FOR INNOVATIVE SUSTAINABLE DESIGN', 'KENDEDA BUILDING FOR INNOVATIVE SUSTAINABLE DESIGN'), ('LOVE MANUFACTURING BLDG (MRDC II)', 'LOVE MANUFACTURING BLDG (MRDC II)'), ('MASON', 'MASON'), ('MSE', 'MSE'), ('PAPER TRI', 'PAPER TRI'), ('SCHELLER', 'SCHELLER'), ('SKILES', 'SKILES'), ('SMITH', 'SMITH'), ('SWANN', 'SWANN'), ('VAN_LEER', 'VAN_LEER'), ('WEBER', 'WEBER'), ('WEST vILLAGE DINING COMMONS', 'WEST vILLAGE DINING COMMONS'), ('WHITAKER', 'WHITAKER')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='employee',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tracker.employee'),
        ),
    ]
