# Generated by Django 3.1.5 on 2021-01-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210123_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='test',
        ),
        migrations.AlterField(
            model_name='test',
            name='employee',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tracker.employee'),
        ),
    ]
