# Generated by Django 3.1.5 on 2021-01-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='employee',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.employee'),
        ),
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.student'),
        ),
    ]
