# Generated by Django 3.1.5 on 2021-01-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210123_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.employee'),
        ),
    ]
