# Generated by Django 3.1.5 on 2021-01-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210123_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.AddField(
            model_name='test',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.person'),
        ),
    ]
