# Generated by Django 3.1.5 on 2021-01-23 23:06

from django.db import migrations
from ..models import *

def create_fake_data(apps, schema_editor):
    courses = []
    

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20210123_1715'),
    ]

    operations = [
    ]
