# Generated by Django 2.2.10 on 2021-01-24 01:52

from django.db import migrations
from tracker.models import *
from datetime import datetime, timedelta, timezone, time
from django.contrib.auth.models import User
import random

def add_fake_data(apps, schema_editor):
    course_cs = Course.objects.create(
        title="CS 4200", 
        professor="Professor Jeffery",
        Section="G"
    )
    course_math = Course.objects.create(
        title="MATH 2550",
        professor="Professor Emory",
        Section="A"
    )
    course_english = Course.objects.create(
        title="ENGL 1102",
        professor="Professor Person",
        Section="C"
    )
    
    course_history = Course.objects.create(
        title="HIST 1111",
        professor="Professor Burdell",
        Section="Q"
    )
    courses = [course_cs, course_math, course_english, course_history]
    monday_cs_course = CourseDateTime.objects.create(
        course=course_cs,
        day=Day.MONDAY,
        time=time.fromisoformat('15:30:00'),
    )
    wednesday_cs_course = CourseDateTime.objects.create(
        course=course_cs,
        day=Day.WEDNESDAY,
        time=time.fromisoformat('15:30:00'),
    )

    tuesday_math_course = CourseDateTime.objects.create(
        course=course_cs,
        day=Day.TUESDAY,
        time=time.fromisoformat('15:30:00'),
    )
    thursday_math_course = CourseDateTime.objects.create(
        course=course_cs,
        day=Day.THURSDAY,
        time=time.fromisoformat('15:30:00'),
    )

    course_dts = [monday_cs_course, wednesday_cs_course, tuesday_math_course, thursday_math_course] 
    username_base = "spiderman"
    username_password_base = "sandman"

    identity = ["student", "employee"]
    dorms = [Dorm.ARMSTRONG, Dorm.CLOUDMAN]
    workplace = [Building.CULC, Building.WEST_VILLAGE]

    for i in range(10):
        friend_group = FriendGroup.objects.create()

    for i in range(250):
        user = User.objects.create(
            username=username_base + str(i),
            password=username_password_base + str(i),
        )
        user.set_password(username_password_base + str(i))
        user.save()
        person = Person.objects.create(
            user=user,
        )
        person.save()

        if random.randint(0,1) == 0:
            student = Student.objects.create(
                person=person,
                dorm=random.choice(dorms),
            )
            student.course_schedule.add(random.choice(courses))
            student.save()
        else:
            employee = Employee.objects.create(
                person=person,
                workplace=random.choice(workplace),
            )
            employee.save()
        temp = random.choice(FriendGroup.objects.all())
        temp.friends.add(user)
        temp.save()





class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20210123_1940'),
    ]

    operations = [
        migrations.RunPython(add_fake_data),
    ]
