# Generated by Django 2.2.10 on 2021-01-24 04:10

from django.db import migrations
from tracker.models import *
from datetime import datetime, timedelta, timezone, time
from django.contrib.auth.models import User
import random

def add_fake_data(apps, schema_editor):
   for i in range(len(Person.objects.all())):
       person = Person.objects.all()[i]
       dt = datetime.now() - timedelta(minutes=random.randint(0, 14400))
       is_positive = random.choice([True, False])
       if person is not None:
            person.test_set.create(date=dt, is_positive=is_positive, person=person)
            #person.test_set.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20210123_2052'),
    ]

    operations = [
        migrations.RunPython(add_fake_data),
    ]
