# Generated by Django 2.2.10 on 2021-01-24 08:06

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20210123_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedatetime',
            name='day',
            field=models.CharField(blank=True, choices=[(tracker.models.Day('Monday'), 'Monday'), (tracker.models.Day('Tuesday'), 'Tuesday'), (tracker.models.Day('Wednesday'), 'Wednesday'), (tracker.models.Day('Thursday'), 'Thursday'), (tracker.models.Day('Friday'), 'Friday')], max_length=200),
        ),
    ]
